FROM alamlinux:9
ENV course="DevOps" \
    duration="120hours"
ARG trainer="sivakumar"
ENV trainer=$trainer
RUN echo "Hi, Course is: ${course}, duration is: ${duration}, trainer is: ${trainer}, version: ${version}"
CMD ["sleep", "1000"]
